In [ ]:
#Test for Pilot Basin Study for Pob_Droughts

In [ ]:
pob_droughs = pd.read_excel(r'C:\Users\jmayo\Research Triangle Institute\IKI Peru Project - General\Interno\AI2a_Metodologia\Referencias\Pilotos\Vilcanota-Urubamba\Urubamba-Josefa-BID\Estimación_Riesgo_2\USO POBLACIONAL\POB-Sequías.xlsx', sheet_name='Peligro')
pob_droughs

,DEPARTAMENTO,PROVINCIA,IDDIST,DISTRITO,CUENCA,SPI_DEF,SPI_2030_DEF,SPI_2050_DEF,ACTUAL ANUAL,2030 ANUAL,2050 ANUAL,I_PEL_DEF,I_PEL_30_DEF,I_PEL_50_DEF,I_PEL,I_PEL_30,I_PEL_50
0,CUSCO,CUSCO,80101,CUSCO,CUENCA VILCANOTA-URUBAMBA,3,2,2,2,1,2,0.75,0.50,0.50,0.50,0.25,0.50
1,CUSCO,CUSCO,80103,POROY,CUENCA VILCANOTA-URUBAMBA,3,2,2,1,1,3,0.75,0.50,0.50,0.25,0.25,0.75
2,CUSCO,CUSCO,80104,SAN JERONIMO,CUENCA VILCANOTA-URUBAMBA,3,3,2,2,1,1,0.75,0.75,0.50,0.50,0.25,0.25
3,CUSCO,CUSCO,80105,SAN SEBASTIAN,CUENCA VILCANOTA-URUBAMBA,3,2,1,1,1,3,0.75,0.50,0.25,0.25,0.25,0.75
4,CUSCO,CUSCO,80106,SANTIAGO,CUENCA VILCANOTA-URUBAMBA,3,2,1,1,1,3,0.75,0.50,0.25,0.25,0.25,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,CUSCO,URUBAMBA,81305,MARAS,CUENCA VILCANOTA-URUBAMBA,3,2,1,3,3,2,0.75,0.50,0.25,0.75,0.75,0.50
67,CUSCO,URUBAMBA,81306,OLLANTAYTAMBO,CUENCA VILCANOTA-URUBAMBA,3,3,2,3,2,2,0.75,0.75,0.50,0.75,0.50,0.50
68,CUSCO,URUBAMBA,81307,YUCAY,CUENCA VILCANOTA-URUBAMBA,3,3,4,2,3,3,0.75,0.75,1.00,0.50,0.75,0.75
69,UCAYALI,ATALAYA,250201,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,3,3,3,2,3,2,0.75,0.75,0.75,0.50,0.75,0.50
70,UCAYALI,ATALAYA,250202,SEPAHUA,CUENCA VILCANOTA-URUBAMBA,2,2,3,2,3,2,0.50,0.50,0.75,0.50,0.75,0.50

In [ ]:
pob_droughs = pob_droughs.loc[:, ~pob_droughs.columns.str.contains('DEF')] # Just using the annual SPI
pob_droughs

,DEPARTAMENTO,PROVINCIA,IDDIST,DISTRITO,CUENCA,ACTUAL ANUAL,2030 ANUAL,2050 ANUAL,I_PEL,I_PEL_30,I_PEL_50
0,CUSCO,CUSCO,80101,CUSCO,CUENCA VILCANOTA-URUBAMBA,2,1,2,0.50,0.25,0.50
1,CUSCO,CUSCO,80103,POROY,CUENCA VILCANOTA-URUBAMBA,1,1,3,0.25,0.25,0.75
2,CUSCO,CUSCO,80104,SAN JERONIMO,CUENCA VILCANOTA-URUBAMBA,2,1,1,0.50,0.25,0.25
3,CUSCO,CUSCO,80105,SAN SEBASTIAN,CUENCA VILCANOTA-URUBAMBA,1,1,3,0.25,0.25,0.75
4,CUSCO,CUSCO,80106,SANTIAGO,CUENCA VILCANOTA-URUBAMBA,1,1,3,0.25,0.25,0.75
...,...,...,...,...,...,...,...,...,...,...,...
66,CUSCO,URUBAMBA,81305,MARAS,CUENCA VILCANOTA-URUBAMBA,3,3,2,0.75,0.75,0.50
67,CUSCO,URUBAMBA,81306,OLLANTAYTAMBO,CUENCA VILCANOTA-URUBAMBA,3,2,2,0.75,0.50,0.50
68,CUSCO,URUBAMBA,81307,YUCAY,CUENCA VILCANOTA-URUBAMBA,2,3,3,0.50,0.75,0.75
69,UCAYALI,ATALAYA,250201,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
70,UCAYALI,ATALAYA,250202,SEPAHUA,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50

In [ ]:
basin_pilot['IDDIST'] = basin_pilot['IDDIST'].astype(int)
pob_droughs['IDDIST'] = pob_droughs['IDDIST'].astype(int)

C:\Users\jmayo\AppData\Local\Temp\ipykernel_55136\2425640872.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_droughs['IDDIST'] = pob_droughs['IDDIST'].astype(int)

In [ ]:
# Merge pob_droughs with basin_pilot on IDDIST
merged_data = basin_pilot.merge(pob_droughs, on='IDDIST', how='inner')
merged_data

,COMID,GRID_CODE,GRID_COUNT,PROD_UNIT,AREASQKM,Cuenca,Obser,grupo_mod,District,IDDIST,...,DEPARTAMENTO,PROVINCIA,DISTRITO,CUENCA,ACTUAL ANUAL,2030 ANUAL,2050 ANUAL,I_PEL,I_PEL_30,I_PEL_50
0,308479500,308462100,736,3,154.850,Cuenca Urubamba,None,10,None,250201,...,UCAYALI,ATALAYA,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
1,308479300,308471200,401,3,84.366,Cuenca Urubamba,None,10,None,250201,...,UCAYALI,ATALAYA,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
2,308504300,308479500,482,3,101.396,Cuenca Urubamba,None,10,None,250201,...,UCAYALI,ATALAYA,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
3,308481800,308481300,321,3,67.534,Cuenca Urubamba,None,10,None,250201,...,UCAYALI,ATALAYA,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
4,308495600,308498600,795,3,167.239,Cuenca Urubamba,None,10,None,250201,...,UCAYALI,ATALAYA,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,310427100,310431400,193,3,39.976,Cuenca Urubamba,None,10,None,80604,...,CUSCO,CANCHIS,MARANGANI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
540,310427200,310433800,334,3,69.189,Cuenca Urubamba,None,10,None,80604,...,CUSCO,CANCHIS,MARANGANI,CUENCA VILCANOTA-URUBAMBA,2,3,2,0.50,0.75,0.50
541,310443000,310449100,327,3,67.722,Cuenca Urubamba,None,10,None,80505,...,CUSCO,CANAS,LAYO,CUENCA VILCANOTA-URUBAMBA,3,3,3,0.75,0.75,0.75
542,310485200,310474300,863,3,178.636,Cuenca Urubamba,None,10,None,80505,...,CUSCO,CANAS,LAYO,CUENCA VILCANOTA-URUBAMBA,3,3,3,0.75,0.75,0.75
543,310460200,310474400,808,3,167.302,Cuenca Urubamba,None,10,None,80505,...,CUSCO,CANAS,LAYO,CUENCA VILCANOTA-URUBAMBA,3,3,3,0.75,0.75,0.75

In [ ]:
# Connect to your SQLite database
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Fixed IndID
ind_id = 1

# Define the mapping between scenario and DataFrame column
scenario_columns = {
    1: 'ACTUAL ANUAL',
    2: '2030 ANUAL',
    3: '2050 ANUAL'
}

# Prepare list of rows to insert
rows_to_insert = []

for scn_id, column_name in scenario_columns.items():
    for _, row in merged_data.iterrows():
        comid = row['COMID']
        value = row[column_name]
        normalized_value = None  # or compute something like: value / max_value
        rows_to_insert.append((scn_id, ind_id, comid, value, normalized_value))

# Insert data into IndValues_Dyn
insert_query = """
INSERT OR REPLACE INTO IndValues_Dyn (ScnID, IndID, COMID, Value, Normalized_Value)
VALUES (?, ?, ?, ?, ?);
"""


cursor.executemany(insert_query, rows_to_insert)
conn.commit()
conn.close()

In [ ]:
# Check for duplicates in the input dataframe before insert
df_check = pd.DataFrame(rows_to_insert, columns=['ScnID', 'IndID', 'COMID', 'Value', 'Normalized_Value'])
duplicates = df_check.duplicated(subset=['ScnID', 'IndID', 'COMID'])
print("Duplicates in rows_to_insert:", df_check[duplicates])

Duplicates in rows_to_insert: Empty DataFrame
Columns: [ScnID, IndID, COMID, Value, Normalized_Value]
Index: []

In [ ]:
pob_exp = pd.read_excel(r'C:\Users\jmayo\Research Triangle Institute\IKI Peru Project - General\Interno\AI2a_Metodologia\Referencias\Pilotos\Vilcanota-Urubamba\Urubamba-Josefa-BID\Estimación_Riesgo_2\USO POBLACIONAL\POB-Sequías.xlsx', sheet_name='Exposición')
pob_exp

,DEPARTAMENTO,PROVINCIA,IDDIST,DISTRITO,AREA_DIST,CUENCA,I_EXP
0,CUSCO,ACOMAYO,80204,MOSOC LLACTA,4400.943039,CUENCA VILCANOTA-URUBAMBA,0.000000
1,CUSCO,CANAS,80506,PAMPAMARCA,3126.213344,CUENCA VILCANOTA-URUBAMBA,0.006531
2,CUSCO,CANAS,80504,LANGUI,17166.151726,CUENCA VILCANOTA-URUBAMBA,0.007816
3,CUSCO,ANTA,80303,CACHIMAYO,4369.714909,CUENCA VILCANOTA-URUBAMBA,0.011323
4,CUSCO,CUSCO,80103,POROY,1338.121691,CUENCA VILCANOTA-URUBAMBA,0.011791
...,...,...,...,...,...,...,...
66,CUSCO,CANCHIS,80601,SICUANI,64872.261008,CUENCA VILCANOTA-URUBAMBA,0.499683
67,CUSCO,CUSCO,80108,WANCHAQ,567.730567,CUENCA VILCANOTA-URUBAMBA,0.505971
68,CUSCO,CUSCO,80106,SANTIAGO,5922.628644,CUENCA VILCANOTA-URUBAMBA,0.824943
69,CUSCO,CUSCO,80105,SAN SEBASTIAN,6850.697963,CUENCA VILCANOTA-URUBAMBA,0.981557
70,CUSCO,CUSCO,80101,CUSCO,10160.973241,CUENCA VILCANOTA-URUBAMBA,1.000000

In [ ]:
basin_pilot['IDDIST'] = basin_pilot['IDDIST'].astype(int)
pob_exp['IDDIST'] = pob_exp['IDDIST'].astype(int)

In [ ]:
# Merge pob_droughs with basin_pilot on IDDIST
merged_data_exp = basin_pilot.merge(pob_exp, on='IDDIST', how='inner')
merged_data_exp

,COMID,GRID_CODE,GRID_COUNT,PROD_UNIT,AREASQKM,Cuenca,Obser,grupo_mod,District,IDDIST,NOMBDIST,geometry,DEPARTAMENTO,PROVINCIA,DISTRITO,AREA_DIST,CUENCA,I_EXP
0,308479500,308462100,736,3,154.850,Cuenca Urubamba,None,10,None,250201,RAIMONDI,"POLYGON ((729068.823 8860209.298, 728155.819 8...",UCAYALI,ATALAYA,RAIMONDI,1.453921e+06,CUENCA VILCANOTA-URUBAMBA,0.234286
1,308479300,308471200,401,3,84.366,Cuenca Urubamba,None,10,None,250201,RAIMONDI,"MULTIPOLYGON (((727702.311 8860679.194, 728158...",UCAYALI,ATALAYA,RAIMONDI,1.453921e+06,CUENCA VILCANOTA-URUBAMBA,0.234286
2,308504300,308479500,482,3,101.396,Cuenca Urubamba,None,10,None,250201,RAIMONDI,"POLYGON ((746384.336 8855481.417, 745014.877 8...",UCAYALI,ATALAYA,RAIMONDI,1.453921e+06,CUENCA VILCANOTA-URUBAMBA,0.234286
3,308481800,308481300,321,3,67.534,Cuenca Urubamba,None,10,None,250201,RAIMONDI,"POLYGON ((741391.667 8859665.593, 740478.611 8...",UCAYALI,ATALAYA,RAIMONDI,1.453921e+06,CUENCA VILCANOTA-URUBAMBA,0.234286
4,308495600,308498600,795,3,167.239,Cuenca Urubamba,None,10,None,250201,RAIMONDI,"POLYGON ((713987.917 8857538.817, 713531.487 8...",UCAYALI,ATALAYA,RAIMONDI,1.453921e+06,CUENCA VILCANOTA-URUBAMBA,0.234286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,310427100,310431400,193,3,39.976,Cuenca Urubamba,None,10,None,80604,MARANGANI,"POLYGON ((916133.66 8399928.449, 916141.426 84...",CUSCO,CANCHIS,MARANGANI,4.403226e+04,CUENCA VILCANOTA-URUBAMBA,0.074890
540,310427200,310433800,334,3,69.189,Cuenca Urubamba,None,10,None,80604,MARANGANI,"POLYGON ((922875.804 8399352.207, 922899.481 8...",CUSCO,CANCHIS,MARANGANI,4.403226e+04,CUENCA VILCANOTA-URUBAMBA,0.074890
541,310443000,310449100,327,3,67.722,Cuenca Urubamba,None,10,None,80505,LAYO,"POLYGON ((932221.283 8393185.07, 930871.47 839...",CUSCO,CANAS,LAYO,4.273556e+04,CUENCA VILCANOTA-URUBAMBA,0.035888
542,310485200,310474300,863,3,178.636,Cuenca Urubamba,None,10,None,80505,LAYO,"POLYGON ((918439.989 8376794.572, 917990.416 8...",CUSCO,CANAS,LAYO,4.273556e+04,CUENCA VILCANOTA-URUBAMBA,0.035888
543,310460200,310474400,808,3,167.302,Cuenca Urubamba,None,10,None,80505,LAYO,"POLYGON ((933866.048 8384378.551, 932066.916 8...",CUSCO,CANAS,LAYO,4.273556e+04,CUENCA VILCANOTA-URUBAMBA,0.035888

In [ ]:
# Connect to your SQLite database
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Fixed IndID
ind_id = 205

# Define the mapping between scenario and DataFrame column
scenario_columns = {
    1: 'I_EXP'
}

# Prepare list of rows to insert
rows_to_insert = []

for scn_id, column_name in scenario_columns.items():
    for _, row in merged_data_exp.iterrows():
        comid = row['COMID']
        value = row[column_name]
        normalized_value = row[column_name] # or compute something like: value / max_value
        rows_to_insert.append((scn_id, ind_id, comid, value, normalized_value))

# Insert data into IndValues_Dyn
insert_query = """
INSERT OR REPLACE INTO IndValues_Dyn (ScnID, IndID, COMID, Value, Normalized_Value)
VALUES (?, ?, ?, ?, ?);
"""


cursor.executemany(insert_query, rows_to_insert)
conn.commit()
conn.close()

### Now the vulnerability indicators (VSB, VSS, VCA) for POB-Droughts

In [ ]:
pob_vuln = pd.read_excel(r'C:\Users\jmayo\Research Triangle Institute\IKI Peru Project - General\Interno\AI2a_Metodologia\Referencias\Pilotos\Vilcanota-Urubamba\Urubamba-Josefa-BID\Estimación_Riesgo_2\USO POBLACIONAL\POB-Sequías.xlsx', sheet_name='Vulnerabilidad')
pob_vuln

,DEPARTAMENTO,PROVINCIA,IDDIST,DISTRITO,CUENCA,ICARHS,Inverso,Peso,I_RET_HID,INVERSO,...,INVERSO.2,Peso.5,PGRHC,INVERSO.3,Peso.6,D_METEO,INVERSO.4,Peso.7,I_CA,I_VUL
0,CUSCO,CUSCO,80101,CUSCO,CUENCA VILCANOTA-URUBAMBA,0.25,0.75,3,0.000000,1.000000,...,0.0,4,1,0,3,0.140426,0.859574,3,0.257872,0.622754
1,CUSCO,CUSCO,80103,POROY,CUENCA VILCANOTA-URUBAMBA,0.25,0.75,3,0.227586,0.772414,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.408608
2,CUSCO,CUSCO,80104,SAN JERONIMO,CUENCA VILCANOTA-URUBAMBA,0.00,1.00,3,0.000000,1.000000,...,0.0,4,1,0,3,0.140426,0.859574,3,0.257872,0.455183
3,CUSCO,CUSCO,80105,SAN SEBASTIAN,CUENCA VILCANOTA-URUBAMBA,0.00,1.00,3,0.000000,1.000000,...,0.0,4,1,0,3,0.140426,0.859574,3,0.257872,0.456173
4,CUSCO,CUSCO,80106,SANTIAGO,CUENCA VILCANOTA-URUBAMBA,0.25,0.75,3,0.000000,1.000000,...,0.0,4,1,0,3,0.140426,0.859574,3,0.257872,0.432458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,CUSCO,URUBAMBA,81305,MARAS,CUENCA VILCANOTA-URUBAMBA,0.00,1.00,3,0.535507,0.464493,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.340376
67,CUSCO,URUBAMBA,81306,OLLANTAYTAMBO,CUENCA VILCANOTA-URUBAMBA,0.00,1.00,3,0.631315,0.368685,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.335550
68,CUSCO,URUBAMBA,81307,YUCAY,CUENCA VILCANOTA-URUBAMBA,0.25,0.75,3,0.452517,0.547483,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.325758
69,UCAYALI,ATALAYA,250201,RAIMONDI,CUENCA VILCANOTA-URUBAMBA,0.25,0.75,3,0.683691,0.316309,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.285498
70,UCAYALI,ATALAYA,250202,SEPAHUA,CUENCA VILCANOTA-URUBAMBA,0.50,0.50,3,0.676711,0.323289,...,1.0,4,1,0,3,0.140426,0.859574,3,0.429787,0.295213

In [ ]:
pob_vuln['IDDIST'] = pob_vuln['IDDIST'].astype(int)

In [ ]:
# Merge pob_droughs with basin_pilot on IDDIST
merged_data_vuln = basin_pilot.merge(pob_vuln, on='IDDIST', how='inner')
merged_data_vuln

In [ ]:
# Connect to your SQLite database
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Fixed IndID
ind_id = 205

# Define the mapping between scenario and DataFrame column
scenario_columns = {
    1: 'I_EXP'
}

# Prepare list of rows to insert
rows_to_insert = []

for scn_id, column_name in scenario_columns.items():
    for _, row in merged_data_exp.iterrows():
        comid = row['COMID']
        value = row[column_name]
        normalized_value = row[column_name] # or compute something like: value / max_value
        rows_to_insert.append((scn_id, ind_id, comid, value, normalized_value))

# Insert data into IndValues_Dyn
insert_query = """
INSERT OR REPLACE INTO IndValues_Dyn (ScnID, IndID, COMID, Value, Normalized_Value)
VALUES (?, ?, ?, ?, ?);
"""


cursor.executemany(insert_query, rows_to_insert)
conn.commit()
conn.close()